language: python
sudo: false
branches:
  only:
    - master
    - develop
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install tox
script:
  - tox --recreate
