initial_pages:
  - url: "http://www.xicidaili.com/nn/[page]"
    page: 1-3
  - url: "http://www.xicidaili.com/nt/[page]"
    page: 1-3
  - url: "http://www.xicidaili.com/wn/[page]"
    page: 1-3
  - url: "http://www.xicidaili.com/wt/[page]"
    page: 1-3
  - url: "http://www.nianshao.me/?stype=1&page=[page]"
    page: 1-40
  - url: "http://www.89ip.cn/tiqu.php?tqsl=1000"
  - url: "http://www.shifengsoft.com/get.php?tqsl=1000"
  - url: "http://www.66ip.cn/mo.php?tqsl=1000"
  - url: "http://www.ip181.com/daili/[page].html"
    page: 1-4
  - url: "http://www.kxdaili.com/ipList/[page].html"
    page: 1-10
  - url: "http://www.bigdaili.com/ipList/[page].html"
    page: 1-10
  - url: "http://www.swei360.com/?page=[page]"
    page: 1-10
  - url: "http://ip84.com/http/[page]"
    page: 1-30
  - url: "http://www.haoip.cc/other/1/[page]"
    page: 1-20
  - url: "http://www.mimiip.com/gngao/[page]"
    page: 1-3
  - url: "http://www.mimiip.com/gnpu/[page]"
    page: 1-3
  - url: "http://www.mimiip.com/gntou/[page]"
    page: 1-3
  - url: "http://www.mimiip.com/hw/[page]"
    page: 1-3
  - url: "http://www.httpdaili.com/mfdl/"

update_pages:
  - url: "http://www.xicidaili.com/nn/1"
  - url: "http://www.xicidaili.com/nt/1"
  - url: "http://www.xicidaili.com/wn/1"
  - url: "http://www.xicidaili.com/wt/1"
  - url: "http://www.nianshao.me/?stype=1&page=1"
  - url: "http://www.89ip.cn/tiqu.php?tqsl=1000"
  - url: "http://www.shifengsoft.com/get.php?tqsl=1000"
  - url: "http://www.66ip.cn/mo.php?tqsl=1000"
  - url: "http://www.ip181.com/daili/[page].html"
    page: 1-2
  - url: "http://www.kxdaili.com/ipList/[page].html"
    page: 1-10
  - url: "http://www.bigdaili.com/ipList/[page].html"
    page: 1-10
  - url: "http://www.swei360.com/?page=[page]"
    page: 1-10
  - url: "http://ip84.com/http/1"
  - url: "http://www.haoip.cc/other/1/[page]"
    page: 1-10
  - url: "http://www.mimiip.com/gngao/1"
  - url: "http://www.mimiip.com/gnpu/1"
  - url: "http://www.mimiip.com/gntou/1"
  - url: "http://www.mimiip.com/hw/1"
  - url: "http://www.httpdaili.com/mfdl/"

scraper_rules:
  - url_match: "xicidaili\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "nianshao\\.me"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "89ip\\.cn"
    proxy_match: "(\\d+\\.\\d+\\.\\d+\\.\\d+:\\d+)"
  - url_match: "shifengsoft\\.com"
    proxy_match: "(\\d+\\.\\d+\\.\\d+\\.\\d+:\\d+)"
  - url_match: "66ip\\.cn"
    proxy_match: "(\\d+\\.\\d+\\.\\d+\\.\\d+:\\d+)"
  - url_match: "ip181\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "kxdaili\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "bigdaili\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "swei360\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "ip002\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "ip84\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "haoip\\.cc"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "mimiip\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"
  - url_match: "httpdaili\\.com"
    proxy_match: "<td[^>]*>\\s*(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s*</td>\\s*<td[^>]*>\\s*(\\d+)\\s*</td>"

spider_headers:
  Connection: "keep-alive"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  User-Agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
  Accept-Encoding: "gzip, deflate, sdch"
  Accept-Language: "zh-CN,zh;q=0.8"
